Alfa patch01 way of the cross
GrupaMedialnaSalwator/kompas.sds pull request #104
Opened 2022-04-09 18:09 UTC by darowsluk

Fix #88 
Fix #97
Fix #99

2022-04-10 19:56 UTC, knutm92 requested changes
The badges stand out on the map and the links are handy, nice!

Other than a small typo- the code looks good.

2022-04-10 19:56 UTC, knutm92 commented on lib/model/mapDatabase.dart
> +            'Bardzo się cieszymy, że nas odwiedzasz i zapraszamy do zwiedzania naszego kompleksu klasztornego w Wyższym Seminarium Duchownym Salwatorianów w Bagnie.\n\nPrzygotowaliśmy dla Ciebie prze
"parkinkowego" typo

2022-04-10 19:56 UTC, knutm92 commented on lib/statics/colors.dart
> +  static const accentContrast = Color.fromARGB(255, 247, 149, 3);
Just an observation- this color seems to fit better than any of the color styles proposed by Figma.

2022-04-10 20:00 UTC, darowsluk commented on lib/model/mapDatabase.dart
> +            'Bardzo się cieszymy, że nas odwiedzasz i zapraszamy do zwiedzania naszego kompleksu klasztornego w Wyższym Seminarium Duchownym Salwatorianów w Bagnie.\n\nPrzygotowaliśmy dla Ciebie prze
Thanks. Fixed it.

2022-04-11 06:24 UTC, knutm92 approved these changes

2022-04-11 06:26 UTC, merged