Drawer and other minor changes
GrupaMedialnaSalwator/kompas.sds pull request #81
Opened 2022-03-18 18:23 UTC by knutm92

fixes #76 
fixes #77 
fixes #70 
fixes #75

2022-03-19 12:05 UTC, darowsluk requested changes
Great changes! Especially the drawer makes a difference together with the image. :)

2022-03-19 12:05 UTC, darowsluk commented on lib/widgets/infoView_widget.dart
> +                              borderRadius: BorderRadius.all(Radius.circular(20)),
Consider using a constant.

2022-03-20 10:52 UTC, darowsluk commented
@knutm92 Sorry, I let myself do a rebase from dev to pickup the latest build changes. This allows for automatic build verification, which reported all checks have passed.

2022-03-20 15:53 UTC, knutm92 commented on lib/view/mapCard_screen.dart
> -      appBar: AppBar(
> @knutm92 Sorry, I let myself do a rebase from dev to pickup the latest build changes. This allows for automatic build verification, which reported all checks have passed.

Thank you, this is actually good as I could jump straight into resolving suggestions, also not feeling in top form after the sickness.

2022-03-20 15:57 UTC, knutm92 commented on lib/view/home_screen.dart
> +          labelColor: Color.fromRGBO(238, 241, 241, 1),
I think this unwanted change sneaked in when I tried to get the color description for our photo editor

2022-03-20 15:58 UTC, knutm92 commented on lib/view/home_screen.dart
> +              LineIcons.walking,
Yep, compass icon is more in line with the app design on the whole :)

2022-03-20 16:05 UTC, knutm92 commented on lib/view/trip_screen.dart
> +                      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
Good suggestion to add the `removeCurrentSnackBar()` I missed that. 

Regarding creating `ScaffoldMessanger` custom class- I'm not sure about it, fixed parameters copied from `ScaffoldMessanger` in `cardHero_widget.dart` didn't fit the `trip_screen` either throwing an error or resulting in button overlay. I'm wondering whether there is  a cleaner way to keep class parameters fixed/constrained to a selected group in dart other than to just use class wrappers, maybe we could discuss this on some occasion.

2022-03-20 16:05 UTC, knutm92 commented on lib/widgets/drawerWidget.dart
> +                      style: AppTextStyles.headerH3White, text: "kompas.sds"),
Good point

2022-03-20 16:05 UTC, knutm92 commented on lib/widgets/drawerWidget.dart
> +                          ),
I added that and reduced the font a bit as well

2022-03-20 16:12 UTC, knutm92 commented
@darowsluk Thanks for the review and rebase, I have updated the issues descriptions and pushed changes suggested in the review!

2022-03-20 19:09 UTC, darowsluk approved these changes
Everything looks good. Let's merge.

2022-03-20 19:09 UTC, darowsluk commented on lib/view/trip_screen.dart
> +                      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
Ok. We can create a separate issue for ScaffoldMessenger.

2022-03-20 19:09 UTC, darowsluk commented on lib/widgets/drawerWidget.dart
> +                          ),
Looks good!

2022-03-20 19:58 UTC, merged